all: TextTrader
TextTrader:
	g++ -std=c++11 -Wno-invalid-source-encoding -I. -L. -L/usr/local/lib -o $@ TextTrader.cpp INIReader.cpp ini.cpp thostmduserapi_se.dylib thosttraderapi_se.dylib -lcurses -lstdc++

clean:
	rm TextTrader
